### ISSUE TITLE
As an end user, I want to be able to clean my workset

### ISSUE THREAD

**Issue by cwulfman** [htrc/torchlite-app#18]
See:
- #33 
- #34 
- #35 
- #36 
- #37

On the dashboard is a checkbox menu of eight choices:

1. Apply Stopwords
2. Make Lowercas
~~3. Lemmatize~~
~~4. Stem~~
~~5. Search and Replace~~
6. Page Features
7. POS Tags
8. Token Count Limits

As for the fltering options, the dashboard does not have an "Apply" button, so the front end, to be idempotent, needs to send a PUT request containing the current set of selected cleaners each time one of the buttons is pressed.

Some of these operations (like Stem and Lemmatize) are standard NLP operations on tokens; others (like POS Tags and Token Count Limits) seem to be filters (e.g., include in the full token list only tokens that are Nouns; include in the token list only tokens that occur more that ten times in the dataset; exclude all tokens that appear in a stop list).  Others, like Make Lowercase and Search and Replace, are basic string operations, but they alter the token data.

"Page Features" refers to the header, footer, and body sections in the EF data; users should be able to choose which of these sections to include in their analyses.

To implement this feature, it will be prudent to break the task down into individual sub-features, by category:

- **filters** (Apply Stopwords, POS Tags, and Token Count Limits, Page Features).  These are just like the operations in the Filters widget; they are added or subtracted from the filter chain. They are pure functions: they are indempotent and free of side-effects, so they do not entail modifying the data.
- **transformers** (Make Lowercase; Lemmatize; Stem; Search and Replace) are very different; they mutate (modify) the data: applying one of these operations yields a new set of new data, which must be managed. These transformers are of two types:
   1. _string operators_: these are operations that are applied to strings of characters: convert _A_  to _a_; _B_ to _b_, and so forth; make context-free substitutions (i.e., /colour/color/, where the only context is the string value of the token).  These basic string operators are part of most programming languages (including Python).
   2. _token operators_: In NLP, the term /token/ usually refers to /word tokens/ -- what we usually think of as words.  Stemming and lemmatization are syntactic operations, and they require programs and databases to execute. Open-source stemmers and lemmatizers exist, but using them adds another layer of complexity to torchlite.  They also assume the data is clean (i.e., that all the tokens are actual words and not dirty-OCR noise)

**suggestion**: a noise filter would probably be a useful thing : a filter that used a dictionary (or dictionaries, in the case of multilingual corpora) to throw out token-strings that are not found in the dictionary.

**Comment by jswatsch** [comment]
HTRC discussed and want to include the following choices:

Apply Stopwords
Make Lowercase
~~Lemmatize~~
~~Stem~~
~~Search and Replace~~
Page Features
POS Tags
Token Count Limits

Clarification on "page features". Page features is a selector between header, body, and footer.

No noise filter at this time.

**Comment by jchristie01** [comment]
See: https://github.com/htrc/torchlite-app/issues/33


For MVP, add dynamic front-end and backend fuctionality to allow users to do the following for adding a stopwords list in the 'Clean the data' section of the side menu:

- Choose from a selection of HTRC-provided stopwords lists in several languages including English
- Choose to upload a custom-named stopwords list (in .txt and .csv format from their local machine OR as a URL to a publicly available stopwords page)
- Download the list they have entered into their selection field 


Related issues: #65 #66 #67 #68 #69

**Comment by jswatsch** [comment]
- Pooja met up with Deren and set up local debug environment
- Couldn't progress because the EF API is down
- Sandeep will help Pooja set up a MongoDB, but Deren opened the TORCHLITE MongoDB so Pooja could use once EF API is working

**Comment by jswatsch** [comment]
Pooja: I am done with backend work for Apply stopwords, pending work is to connect backend and front end for the same.

Additional notes (Sandeep): SPS and PPS met last week to troubleshoot Pooja’s dev environment, and connection to -dev Mongo; that had a blocker, which Deren resolved (by opening to the world – only needed for development work)

**Comment by jchristie01** [comment]
Pooja: Facing current issues on the backend. Confusing error as roadblock. 
Deren: Issue should be resolved. MongoDB can be opened up on a weekly basis so that it can always stay open.

**Comment by jswatsch** [comment]
Pooja needs some code debugging with Deren.

**Comment by jswatsch** [comment]
Pooja and Deren worked on debugging it with Deren on 11/6/2024. Volume data is still comin in is NULL, and will continue to work on debugging 11/7/2024
- Frontend and backend are connecting now

**Comment by jswatsch** [comment]
Main functionality that is complete: 
- [x] Selecting a language from the dropdown is complete
- [x] Confirmed that the words are removed on the backend

Main functionality that is not complete:

- [ ] Upload custom list


Still a few bugs:
- [ ] state is not maintained when the sidebar is closed
- [ ] URL status is not updated when stop words is applied

**Comment by jswatsch** [comment]
- Pooja and Deren decided to take a new approach and will send a list of strings.
- Bugs need more investigation

**Comment by jswatsch** [comment]
From slack:
Hi All,
I will not be able to join today’s torchlite call as I have to attend a mandatory meeting.
WRT my updates I have to create a PR for all the changes for stopwords to be merged into dev including custom stopwords. I will be able to join next week’s call for the demo of custom stopwords to the team.
I will talk to Deren for PR review.
Thanks.

**Comment by jswatsch** [comment]
There is a pull request. Deren is reviewing.
