### ISSUE TITLE
As an end user, I want a widget that displays the publication dates of volumes in my workset on a timeline

### ISSUE THREAD

**Issue by cwulfman** [htrc/torchlite-app#20]
The [dashboard wireframe](https://sq8xm2.axshare.com/?id=kjydh9&p=home) shows a [mirrored beeswarm visualization](https://observablehq.com/@d3/beeswarm-mirrored).   This visualization uses dot placement along the x axis to show time and dot color and the number of dots to interpret two other categorical variable (unspecified in the wireframe). The wireframe includes a stock slider whose function is also unspecified.

The [SoW](https://docs.google.com/document/d/1iroID148ZxH1wh1SgJ5T217Dtteyg7ApJIo46JB5TEE/edit#) simply specifies that Agile will produce _a widget that displays a timeline of publication from publication dates indicated in the Extracted Features set (the “Timeline Widget”)._  Is the mirrored beeswarm simply a placeholder for a timeline widget, or should it have been specified in the SoW?

Assuming HTRC meant to specify the mirrored beeswarm visualization, then several questions need to be answered before it can be developed:

- [ ] **What are the categorical variables being visualized?** Publication date (metadata.pubDate in the EF dataset) is clearly what is intended to be projected onto the x axis of the graph. The placement of the dots on the y axis, their number, and their color, are not specified, but each dot (or lozenge: must the markers be lozenges or can they be simple dots?) is probably meant to correspond to a publication. Color could be any of a number of categorical variables, the most likely being place of publication; however, see below for notes on using pubPlace from the EF dataset.
- [ ] **What is the slider intended to do?**  It could be used to shift the window on the graph left and right, to show earlier and later dates; it could be used to change date granularity (though that pubDate data is simply years, limiting the granularity to four states: yearly, by decade, by century, and by millenium); it could be used to change geopolitical resolution (see below).

There are several D3 implementations of this visualization, including [this one](https://observablehq.com/@d3/beeswarm-mirrored) on Observable, and [this one by Martin Heinz](https://martinheinz.dev/blog/27).

### The Problem of pubPlace granularity
To use the color dimension to indicate pubPlace effectively, the pubPlaces need to have the same geopolitical type: continent, country, state, city, etc.  The pubPlaces in the EF data are varied: some are countries (England); some are American states (New Jersey); some are cities (Washington, D.C.) Because the pubPlaces are linked data, it should be possible to write Resolvers that can establish what country a city or state is in; in theory, one might be able to look up the name of the publisher in an encyclopedia and make a guess about what city they were based in, but that is likely to be time-consuming and error-prone: not something to be done at runtime.

### Dependencies

- [ ] front-end of pub-date widget (https://github.com/htrc/torchlite-frontend/issues/5)
- [x] back-end of pub-date widget (https://github.com/htrc/torchlite-backend/issues/10)

- [ ] pre-defined Extracted-Features worksets
- [ ] an API or convention for making a list of those worksets available to Torchlite
- [ ] a front-end workset picker (https://github.com/htrc/torchlite-frontend/issues/4)
- [x] a back-end API end point for setting a dashboard's current workset
- [x] a handler for that end point

**Comment by cwulfman** [comment]
For now, assume the Observable beeswarm implementation (black & white); back end sends title and pubdate; front end javascript takes care of rest. Interactivity: toggle between years, decades

**Comment by hctrgnzlz** [comment]
From our March 28th Meeting:

- Beeswarm implementation starting with black and white (no colors)
- Dashboard wireframe is not final, if beeswarm proves to be too much hassle to implement other D3 options can be used
- Slider is intended to narrow down or expand dates on the timeline (century, decades, years), this should be done through javascript and not calls to the backend
- Filters vs Facets: facets include (genre, resource type, category (library of congress), availability

SPRINTS
FIRST SPRINT
- simple histogram 
- toggle that lets you switch between granularity of decades - interactivity in the first version 

SECOND SPRINT
- workset picker

THIRD SPRINT
- workset filter

**Comment by jswatsch** [comment]
HTRC reviewed Hector's notes from March 28 meeting and have no changes.
