### ISSUE TITLE
Production instance

### ISSUE THREAD

**Issue by sandeep-ps** [htrc/torchlite-app#81]
This epic is a catch-all for all tasks for setting up production instances. 

- [x] https://github.com/htrc/torchlite-app/issues/72
- [x] https://github.com/htrc/torchlite-argocd/issues/16
- [ ] https://github.com/htrc/torchlite-argocd/issues/13

**Comment by jswatsch** [comment]
Complete, but there are still some bugs.
